[book]
title    = "zstdx Development Handbook"
authors  = ["lxl66566"]
language = "en"
src      = "src"

[build]
build-dir      = "book"
create-missing = false

[output.html]
default-theme        = "navy"
preferred-dark-theme = "navy"
smart-punctuation    = false
