//! Shared corpus access and setup helpers for the gungraun benches.
//!
//! The benches slice `bench/corpus` (regenerate with `bench/gen_corpus.sh`)
//! down to [`SLICE`] bytes so a full valgrind sweep stays in the minutes
//! range, and produce the compressed input frames in the setup expressions
//! passed to `#[bench]` attributes — gungraun only counts instructions
//! inside the benchmark function, so neither the file reads, the frame
//! production nor the cross-implementation correctness gates pollute the
//! metrics.

use std::{fs, path::PathBuf};

use zstdx::{EncoderOptions, Level, decoding::FrameDecoder};

/// Corpus shapes generated by `bench/gen_corpus.sh`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Shape {
    /// Semi-structured records.
    Json,
    /// Source tree tiled: long-range repeats.
    Text,
    /// 16-byte alphabet: heavy short matches.
    Skewed,
    /// Incompressible.
    Random,
    /// Maximally redundant.
    Zeros,
}

pub const SHAPES: [Shape; 5] = [
    Shape::Json,
    Shape::Text,
    Shape::Skewed,
    Shape::Random,
    Shape::Zeros,
];

impl Shape {
    pub const fn raw_name(self) -> &'static str {
        match self {
            Shape::Json => "json",
            Shape::Text => "text",
            Shape::Skewed => "skewed",
            Shape::Random => "random",
            Shape::Zeros => "zeros",
        }
    }
}

/// Raw bytes fed to every benchmark: the first slice of a corpus shape.
pub const SLICE: usize = 1 << 20;

/// The benchmark ladder: `(zstdx level, matching libzstd level)`.
pub const LADDER: [(Level, i32); 6] = [
    (Level::Fastest, 1),
    (Level::Fast, 3),
    (Level::Balanced, 9),
    (Level::Best, 13),
    (Level::Opt, 17),
    (Level::Ultra, 19),
];

/// Decode benchmark input: a frame plus the exact-size output buffer the
/// benchmark function decodes into.
pub struct DecodeCase {
    pub compressed: Vec<u8>,
    pub out: Vec<u8>,
    pub raw_len: usize,
}

pub fn raw_slice(shape: Shape) -> Vec<u8> {
    let mut path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    path.push("../../bench/corpus");
    path.push(format!("{}.raw", shape.raw_name()));
    let raw = fs::read(&path).unwrap_or_else(|e| {
        panic!(
            "cannot read corpus file {}: {e}; regenerate with bench/gen_corpus.sh",
            path.display()
        )
    });
    assert!(
        raw.len() >= SLICE,
        "corpus file {} is smaller than the {SLICE}-byte benchmark slice",
        path.display()
    );
    raw[..SLICE].to_vec()
}

/// Setup for decode benchmarks of interop frames: a libzstd-compressed
/// slice, gated by decoding it back through zstdx before it is handed to
/// the measured function.
pub fn zstd_frame(shape: Shape, level: i32) -> DecodeCase {
    let raw = raw_slice(shape);
    let compressed = zstd::bulk::compress(&raw, level).unwrap();
    let mut out = vec![0u8; raw.len()];
    let mut dec = FrameDecoder::new();
    let n = dec.decode_all(&compressed, &mut out).unwrap();
    assert_eq!(
        &out[..n],
        &raw[..],
        "zstdx gate mismatch for {shape:?} l{level}"
    );
    DecodeCase {
        compressed,
        out,
        raw_len: raw.len(),
    }
}

/// Setup for decode benchmarks of own frames: a zstdx-compressed slice,
/// gated through both decoders so a broken encoder fails the bench run
/// instead of producing garbage metrics.
pub fn zstdx_frame(shape: Shape, level: Level) -> DecodeCase {
    let raw = raw_slice(shape);
    let compressed = zstdx::bulk::compress_with(&raw, &EncoderOptions::new(level).checksum(false));
    let mut back = Vec::with_capacity(raw.len() + 16);
    FrameDecoder::new()
        .decode_all_to_vec(&compressed, &mut back)
        .unwrap();
    assert_eq!(
        &back[..],
        &raw[..],
        "zstdx roundtrip mismatch for {shape:?}"
    );
    let mut zback = Vec::new();
    zstd::stream::copy_decode(compressed.as_slice(), &mut zback).unwrap();
    assert_eq!(
        &zback[..],
        &raw[..],
        "zstd roundtrip mismatch for {shape:?}"
    );
    DecodeCase {
        compressed,
        out: vec![0u8; raw.len()],
        raw_len: raw.len(),
    }
}
